BigQuery Destination Integration
buildable/connections pull request #204
Opened 2023-02-08 17:06 UTC by hzerrad

2023-02-08 21:30 UTC, paulkr requested changes

2023-02-08 21:30 UTC, paulkr commented on tests/setup-tests.ts
> +dotenv.config({ path: '/Users/hzerrad/Freelance/buildable/buildable-connections/.env' });
Looks like you left this path in by accident!

2023-02-08 21:36 UTC, hzerrad commented on tests/setup-tests.ts
> +dotenv.config({ path: '/Users/hzerrad/Freelance/buildable/buildable-connections/.env' });
Oops, my bad 😅 will fix it right away

2023-02-09 19:33 UTC, paulkr approved these changes

2023-02-09 19:33 UTC, merged