Added template for retrieving Sellix blacklists
buildable/connections pull request #41
Opened 2022-05-28 17:38 UTC by flancast90

Hey @paulkr ,

I've added a template for the [Sellix API's](https://developers.sellix.io/#introduction) GET blacklist for specified user. Let me know if there's anything you need changed, or anything you have questions about. I've tested in a flow already, and can verify it works as expected. 

Thanks!

2022-05-30 22:23 UTC, paulkr requested changes
Good work, I've added a few comments!

2022-05-30 22:23 UTC, paulkr commented on templates/sellix/get-blacklist/config.json
> +  "image": "https://cdn.sellix.io/static/logo/sellix-logo-black-smaller.png",
This logo for Sellix wouldn't render very well as a Node template icon. I've designed one for you here that you can use instead:

`"https://assets.buildable.dev/catalog/node-templates/sellix.svg"`

2022-05-30 22:23 UTC, paulkr commented on templates/sellix/get-blacklist/config.json
> +  "category": "custom",
The category should be `"ecommerce"`.

2022-05-30 22:23 UTC, paulkr commented on templates/sellix/get-blacklist/input.js
> +    url: "https://dev.sellix.io/v1/blacklists", // Required
It would be a good idea to pass the base url as an environment variable instead of being explicit in the input.

2022-05-30 22:41 UTC, flancast90 commented on templates/sellix/get-blacklist/input.js
> +    url: "https://dev.sellix.io/v1/blacklists", // Required
That makes sense, but I think it could get confusing to end-users, not to mention they then have to go through the docs to find the correct base url. I think a better idea would be to have an optional environment variable, which, if not set, defaults to the hardcoded one (current). What do you think about this?

2022-05-31 01:00 UTC, flancast90 commented
@paulkr , I've added the changes you mentioned, as well as opened #42 about accepting default env values for better future readability.

2022-06-03 16:51 UTC, paulkr commented on templates/sellix/get-blacklist/config.json
> +  "image": "https://cdn.sellix.io/static/logo/sellix-logo-black-smaller.png",
As mentioned in the previous review, the logo URL should be: 

https://assets.buildable.dev/catalog/node-templates/sellix.svg

2022-06-03 16:56 UTC, paulkr requested changes

2022-06-03 16:56 UTC, paulkr commented on templates/sellix/get-blacklist/config.json
> +  "envVars": {
The `envVars` are not set properly. It should look like this:

```json
{
  "envVars": {
    "SELLIX_API_KEY": {
      "development": "",
      "production": ""
    },
    "SELLIX_API_BASE": {
      "development": "https://dev.sellix.io/v1",
      "production": "https://dev.sellix.io/v1"
    }
  }
}
```

2022-06-03 16:56 UTC, paulkr commented on templates/sellix/get-blacklist/config.json
> +  "image": "https://cdn.sellix.io/static/logo/sellix-logo-black-smaller.png",
As mentioned in the previous review, the logo URL should be: 

https://assets.buildable.dev/catalog/node-templates/sellix.svg

2022-06-08 20:29 UTC, flancast90 commented on templates/sellix/get-blacklist/config.json
> +  "image": "https://cdn.sellix.io/static/logo/sellix-logo-black-smaller.png",
Whoops! I thought I'd done this, must've forgot. Fixed in the latest commit.

2022-06-29 19:36 UTC, flancast90 commented
@paulkr , I fixed that last set of issues a while back. Could I have further feedback on this? Thanks!

2022-08-11 19:06 UTC, paulkr requested changes
Hey @flancast90, the structure of the repo and the input/run files has been updated since the migration to Buildable V3. You can refer to the contribution guidelines for action templates found here: https://github.com/buildable/connections/blob/main/actions/docs/CONTRIBUTING.md

2022-08-30 17:06 UTC, paulkr commented
Closing as the PR needs to be redone for the updated version of Buildable.

2022-08-30 17:06 UTC, closed without merging