feat: created ClickUp teams template
buildable/connections pull request #43
Opened 2022-06-03 02:09 UTC by YoussefLaunchUp

###  ClickUp list teams template

I have created a template to retrieve a ClickUp workspace team info.  The teams object has information about each of the users in the team as well as info about the team itself. 

More info on the ClickUp API: https://clickup.com/api

Placed it under a new folder for ClickUp with ClickUp being the platform as well for future ClickUp template work.

I have tested the template within buildable. 
![image](https://user-images.githubusercontent.com/104530466/171772453-05fa24cd-a4f7-4433-a474-a6f866fdb0ab.png)

I am unsure about which tags to add are required.

Was unsure where the icons should be stored so I uploaded them to a public Repo and linked to that.

2022-06-03 17:40 UTC, moekatib commented on templates/clickup/teams-list/run.js
> +      url: "https://api.clickup.com/api/v2/team",
It would be ideal if the URL were provided via the input. Doing so will make future changes easier. An even better approach is storing the URL as an envVar (with the value provided):
```json
{
  "name": "teams",
...
  "envVars": {
    "CLICKUP_API_TOKEN": {
      "development": "",
      "production": ""
    }, "CLICKUP_API_URL": {
      "development": "https://api.clickup.com/api/v2/",
      "production": "https://api.clickup.com/api/v2/"
    }
  },
...
}
```
Storing it in an envVar enables the ability to make a single change that will immediately apply everywhere.

2022-06-03 18:03 UTC, paulkr requested changes

2022-06-03 19:32 UTC, YoussefLaunchUp commented on templates/clickup/teams-list/run.js
> +      url: "https://api.clickup.com/api/v2/team",
Sounds good, updated the config file and Run file to use an envVar for the CLICKUP_API_URL

2022-06-03 19:33 UTC, YoussefLaunchUp commented on templates/clickup/teams-list/config.json
> +  "envVars": {
Sounds good, updated the config file and Run file to use an envVar for the CLICKUP_API_URL

2022-06-03 19:34 UTC, YoussefLaunchUp commented on templates/clickup/teams-list/config.json
> +  "tags": ["business","project managment","agile"],
Oops, updated the tags with the one you recommended.

2022-06-03 19:34 UTC, YoussefLaunchUp commented on templates/clickup/teams-list/config.json
> +  "category": "",
changed category to `"productivity"`

2022-06-03 19:35 UTC, YoussefLaunchUp commented on templates/clickup/teams-list/config.json
> +  "image": "https://github.com/LaunchUpCorp/PublicAssets/blob/main/ClickUpIcons/desktop%20app%20-%20white%20rounded.svg",
updated URL to image

2022-06-08 13:29 UTC, paulkr requested changes

2022-06-08 13:29 UTC, paulkr commented on templates/clickup/teams-list/run.js
> +      url: `${CLICKUP_API_URL}/team`,
In your config, you've set the value of `CLICKUP_API_URL` to `"https://api.clickup.com/api/v2/"` so when passing a URL to axios, you are currently passing an additional slash after the version. You can either update the config value or the `run.js` code.

2022-06-08 23:34 UTC, YoussefLaunchUp commented on templates/clickup/teams-list/run.js
> +      url: `${CLICKUP_API_URL}/team`,
removed final / from url.

2022-06-08 23:34 UTC, YoussefLaunchUp commented on templates/clickup/teams-list/config.json
> +  "title": "List all teams in a ClickUp workspace",
Updated title.

2022-08-11 19:06 UTC, paulkr requested changes
Hey @YoussefLaunchUp, the structure of the repo and the input/run files has been updated since the migration to Buildable V3. You can refer to the contribution guidelines for action templates found here: https://github.com/buildable/connections/blob/main/actions/docs/CONTRIBUTING.md

2022-08-30 17:05 UTC, paulkr commented
Closing as the PR needs to be redone for the updated version of Buildable.

2022-08-30 17:05 UTC, closed without merging