PagerDuty Integration
buildable/connections pull request #58
Opened 2022-08-11 16:13 UTC by andrewlor

To get the test suite running, set up the following environment variables (also described in auth section of integration definition):
- PAGERDUTY_API_TOKEN
  - api token from your pagerduty account
- PAGERDUTY_FILTER_TYPE
  - account_reference, service_reference or team_reference.
- PAGERDUTY_FILTER_ID
  - Only required for service_reference or team_reference, in which case it will be your service or team ID.

#### Test suite run:
![Screen Shot 2022-08-11 at 9 54 38 AM](https://user-images.githubusercontent.com/8475244/184178589-efd20289-6a7e-424f-bff0-c1cbc9bcb529.png)

2022-08-11 20:56 UTC, paulkr requested changes
Great job so far!

2022-08-11 20:56 UTC, paulkr commented on sources/catalog/pagerduty/config.json
> +      "name": "PAGERYDUTY_FILTER_TYPE",
To render a dropdown with these options, this object should be:

```
{
  "name": "PAGERDUTY_FILTER_TYPE",
  "type": "select",
  "options": [
    {
      "name": "Account Reference",
      "value": "account_reference"
    },
    {
      "name": "Service Reference",
      "value": "service_reference"
    },
    {
      "name": "Team Reference",
      "value": "team_reference"
    }
  ],
    "label": "Select the Filter Type"
}
```

2022-08-11 20:56 UTC, paulkr commented on sources/catalog/pagerduty/config.json
> +      "name": "PAGERYDUTY_FILTER_TYPE",
There is a typo here- it should be: `PAGERDUTY_FILTER_TYPE`

2022-08-11 20:56 UTC, paulkr commented on sources/catalog/pagerduty/config.json
> +      "name": "PAGERYDUTY_FILTER_ID",
Typo: `PAGERDUTY_FILTER_ID`

2022-08-11 20:56 UTC, paulkr commented on sources/catalog/pagerduty/config.json
> +      "label": "The id of the object being used as the filter. This field is required for all filter types except account_reference.",
The label should be: "Enter your PagerDuty Filter ID. This field is not required for Account Reference filters"

2022-08-11 20:56 UTC, paulkr commented on sources/catalog/pagerduty/config.json
> +    "id": "_.body.event.id",
This refers to the id of the webhook. Since you are passing `webhookData: response.data.webhook_subscription` in the `init` method, this value should be `_.body.id`

2022-08-11 20:56 UTC, paulkr commented on sources/catalog/pagerduty/PagerDuty.ts
> +        message: "Connection to PagerDuty API is healthy",
To be consistent with other source connections, this message should be `"Connection tested successfully!"`

2022-08-11 21:34 UTC, andrewlor commented on sources/catalog/pagerduty/config.json
> +      "name": "PAGERYDUTY_FILTER_ID",
Whoops!

2022-08-11 21:36 UTC, andrewlor commented on sources/catalog/pagerduty/config.json
> +    "id": "_.body.event.id",
Makes sense. I got it confused with the event id.

2022-08-15 17:26 UTC, paulkr requested changes
Please update the tests as needed with the changes

2022-08-15 18:03 UTC, andrewlor commented on sources/catalog/pagerduty/PagerDuty.ts
> +    return { webhook: response.data, events: response.data.webhook_subscription.events };
Oh thanks, good catch. I updated both to `response.data.webhook_subscription` and updated the tests for each to assert that `webhook.id` is present in the return object from these functions.

2022-08-15 21:02 UTC, paulkr approved these changes
Looks great!

2022-08-15 21:02 UTC, merged