[WIP] Jira integration
buildable/connections pull request #60
Opened 2022-08-15 12:41 UTC by GildedHonour

2022-08-15 16:11 UTC, moekatib requested changes
Remarkable so far. Just added couple comments.

2022-08-15 16:11 UTC, moekatib commented on sources/catalog/jira/Jira.ts
> +    }
Same as above 👆

2022-08-15 16:11 UTC, moekatib commented on sources/catalog/jira/Jira.ts
> +    const webhooks = await this.jira.webhooks.getDynamicWebhooksForApp({
Is it possible to get the count of webhooks first and then set the maxResults dynamically? If the actual number of webhooks is larger than the amount allowed by Jira then we can loop and get the next pages then filter to get the one we need and return it. This will ensure not having a use case where no webhook is returned. 

Alternatively, and if Jira's maxResults is high, then set it to the highest value possible.

2022-08-15 16:11 UTC, moekatib commented on sources/catalog/jira/Jira.ts
> +      maxResults: maxResults,
Small, but no need for the double maxResults, and startAt.

2022-08-15 16:11 UTC, moekatib commented on sources/catalog/jira/config.json
> +  "eventSchema": {
This might be not the data we need, but @paulkr will provide a better comment than me :)

2022-08-15 16:11 UTC, moekatib commented on sources/catalog/jira/config.json
> +  "eventSchema": {
This is usually the shape of the payload that Jira will send to us when an event occurs.

2022-08-15 16:11 UTC, moekatib commented on sources/catalog/jira/Jira.ts
> +    try {
@paulkr thoughts on this 👆?

2022-08-15 23:10 UTC, paulkr requested changes

2022-08-15 23:10 UTC, paulkr commented on sources/catalog/jira/Jira.ts
> +    try {
Agreed. Adding an additional fallback to create a webhook with the initial events (they can be grabbed from the `getSubscribedEvents` method prior to the delete) is what should be done. If that fails, simply return:

```
{
  webhook: {},
  events: []
}
```

2022-08-15 23:10 UTC, paulkr commented on sources/catalog/jira/Jira.ts
> +      throw new Error("Error updating a webhook (delete/create); Note that Jira doesn't support updating webhooks.");
Should not throw an error here. Return the above comment's response

2022-08-15 23:10 UTC, paulkr commented on sources/catalog/jira/Jira.ts
> +      throw new Error("Error updating a webhook (delete); Note that Jira doesn't support updating webhooks.");
Should not throw an error here. Should return 
```
{
  webhook: {},
  events: []
}
```

2022-08-16 00:37 UTC, GildedHonour commented on sources/catalog/jira/Jira.ts
> +    const webhooks = await this.jira.webhooks.getDynamicWebhooksForApp({
> Is it possible to get the count of webhooks first and then set the maxResults dynamically?
Get a number of its own - no. It's possible to check if there're more results left, though.

We can pass quite a big number. However, what should happen if there're really a lot of results? Will a user be to wait for 100k results, theoretically, to get returned? It may not be likely, but theoretically it can happen.

2022-08-16 00:39 UTC, GildedHonour commented on sources/catalog/jira/Jira.ts
> +      maxResults: maxResults,
What do you mean?

2022-08-16 00:40 UTC, GildedHonour commented on sources/catalog/jira/config.json
> +  "eventSchema": {
Ok, I see

2022-08-16 00:41 UTC, GildedHonour commented on sources/catalog/jira/Jira.ts
> +    const webhooks = await this.jira.webhooks.getDynamicWebhooksForApp({
>Alternatively, and if Jira's maxResults is high, then set it to the highest value possible.

It's int32, therefore we can possible use int32.MaxValue

2022-08-17 02:14 UTC, GildedHonour commented
It's turned out that calling webhook related function is possible via OAuth2 which required creating a simple Jira application. That is, simply using REST API with basic authentication (email + api token) isn't allowed. I'll get an error

>"Only apps can access this resource.",

https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-webhooks/#api-group-webhooks


Solution: I'll try to create a simple app, to obtain OAuth2 token and used it for testing.

2022-08-18 14:15 UTC, GildedHonour commented
After trial and error...... it's done

2022-08-18 14:33 UTC, GildedHonour commented
In order to run the tests,  a Jira environment will have to be preppared in Jira.
Nonetheless, all the tests are passing

![Screenshot_2022-08-18_11-30-18](https://user-images.githubusercontent.com/2032888/185421375-d0cd80ca-ca3b-47aa-9372-5e0d0b72b332.png)

2022-08-20 01:04 UTC, GildedHonour commented
@paulkr @moekatib let's finish reviewing my PR, shell we?

2022-08-22 21:29 UTC, paulkr requested changes
Please remove the `jira_oauth2_screen.png` and `README.md` files. We have made note of them, thanks.

2022-08-22 21:29 UTC, paulkr commented on sources/catalog/jira/config.json
> +  "events": [
This list of events is not complete. The full list can be found here:

https://developer.atlassian.com/server/jira/platform/webhooks/#configuring-a-webhook

2022-08-22 21:29 UTC, paulkr commented on sources/catalog/jira/config.json
> +  },
The config is missing the entire `paths` object...

2022-08-22 21:29 UTC, paulkr commented on sources/catalog/jira/README.md
> +# Jira API
No files other than the changelog, class and config should be added. Please remove this file

2022-08-22 21:29 UTC, paulkr commented on sources/catalog/jira/config.json
> +      "placeholder": "1234567890abc"
This placeholder should be in a similar structure to the actual authentication field

2022-08-22 21:29 UTC, paulkr commented on sources/catalog/jira/config.json
> +      "placeholder": "my-project-123"
This placeholder should be in a similar structure to the actual authentication field

2022-08-22 21:29 UTC, paulkr commented on sources/catalog/jira/Jira.ts
> +      throw new Error("Unable to establish a connection to Jira");
Throw the error message as well:

```
throw new Error(
  "Unable to establish a connection to Jira: " + (err as Error).message
);
```

2022-08-22 21:58 UTC, GildedHonour commented on sources/catalog/jira/config.json
> +      "placeholder": "1234567890abc"
For instance? 

The actual OAUTH2_ACCESS_TOKEN is around several hundred characters long, and it's random values anyway.

2022-08-22 22:33 UTC, GildedHonour commented
done

2022-08-22 22:35 UTC, GildedHonour commented
` .env.sample ` keeps getting unresolved, although I've resolved it manually several times already, locally and here

2022-08-23 19:24 UTC, GildedHonour commented
done @paulkr

2022-08-24 15:18 UTC, paulkr approved these changes

2022-08-24 15:19 UTC, merged