ADD - added Webflow integration
buildable/connections pull request #66
Opened 2022-08-17 18:13 UTC by sromic

Added Webflow integration

2022-08-18 15:46 UTC, paulkr requested changes
Great job so far!

2022-08-18 15:46 UTC, paulkr commented on sources/catalog/webflow/config.json
> +    "event": null,
The path for the event name cannot be null

2022-08-18 15:46 UTC, paulkr commented on sources/catalog/webflow/webflow.ts
> +type WebFlowTriggerType =
You are currently managing the events in the class as well. They should not be specified here (since they are located in the config).

2022-08-18 15:46 UTC, paulkr commented on .env.sample
> +WEBFLOW_VERSION=1.0.0
The `WEBFLOW_VERSION` is not needed

2022-08-18 15:52 UTC, sromic commented on sources/catalog/webflow/config.json
> +    "event": null,
The problem here is that Webflow's received webhook events do not have event type provided. So we can not tell just based on a received payload what that is unless we do a schema validation per event type.

2022-08-18 15:53 UTC, sromic commented on sources/catalog/webflow/webflow.ts
> +type WebFlowTriggerType =
Well this is just to make Webflow's webhook model type safe within a codebase.

2022-08-18 15:53 UTC, sromic commented on .env.sample
> +WEBFLOW_VERSION=1.0.0
Sure, yeah anyways this is an optional param.

2022-08-18 18:01 UTC, paulkr requested changes

2022-08-18 18:01 UTC, paulkr commented on sources/catalog/webflow/webflow.ts
> +type WebFlowTriggerType =
We don't want multiple places to manage webhook names. This should only be in the config file.

2022-08-18 18:02 UTC, paulkr commented on sources/catalog/webflow/config.json
> +    "event": null,
`_.query.event` will suffice if you pass in a query param to the webhookUrl whenever creating

2022-08-22 20:57 UTC, paulkr requested changes

2022-08-22 20:57 UTC, paulkr commented on sources/catalog/webflow/types.ts
> +export type WebflowWebook = {
This must be moved into the webflow class rather than kept in a new file.

2022-08-22 21:27 UTC, sromic commented on sources/catalog/webflow/types.ts
> +export type WebflowWebook = {
I moved this out in order to keep this Webflow class as clean as possible by moving "external" types to a new file.
But if you then it's better to have external types defined within this class I'll move then back :)

2022-08-22 21:31 UTC, paulkr commented on sources/catalog/webflow/types.ts
> +export type WebflowWebook = {
Good thought but we would like to keep all source connection class logic within the singular class file

2022-08-22 21:32 UTC, paulkr commented on sources/catalog/webflow/types.ts
> +export type WebflowWebook = {
Ensure that the types file you created is also deleted

2022-08-22 21:33 UTC, paulkr commented
Ensure that the types file you created is also deleted

2022-08-22 21:33 UTC, sromic commented on sources/catalog/webflow/types.ts
> +export type WebflowWebook = {
Yup, deleted types file and moved them back to the integration class.

2022-08-22 22:34 UTC, paulkr requested changes
Please update the tests accordingly to the requested changes.

2022-08-22 22:34 UTC, paulkr commented on sources/catalog/webflow/config.json
> +      "name": "WEBFLOW_SITE_ID",
Getting the site ID is not a very straightforward task. This should be removed and programmatically retrieved within the class file.

2022-08-22 22:34 UTC, paulkr commented on sources/catalog/webflow/types.ts
> +export type WebflowWebook = {
Since this has been added into the class, this file can be deleted.

2022-08-22 22:34 UTC, paulkr commented on sources/catalog/webflow/webflow.ts
> +    WEBFLOW_SITE_ID,
Remove the site id

2022-08-22 22:34 UTC, paulkr commented on sources/catalog/webflow/webflow.ts
> +
Webflow allows you to get the Site ID from an endpoint if you pass the access token as a param.

https://api.webflow.com/sites?api_version=1.0.0&access_token=${WEBFLOW_API_TOKEN}

That will return an object that looks like: 

```
{
  "_id":"62fe753c20c37077cb966e56",
  "createdOn":"2022-08-18T17:22:04.027Z",
  "name":"Paul's Five-Star Site",
  "shortName":"pauls-five-star-site-0a5668",
  "lastPublished":"2022-08-18T17:58:17.027Z",
  "previewUrl":"https://screenshots.webflow.com/sites/62fe753c20c37077cb966e56/20220818175817_9c257e06190e0d63a38bacbfc4152d52.png",
  "timezone":"America/Toronto"
}
```

Since you can get the SITE ID from the `_id`  field, create a helper function to make this request where needed.

2022-08-23 12:02 UTC, sromic commented on sources/catalog/webflow/webflow.ts
> +
Okay, yeah, site ID is probably hard to get at the starting point.
With the above endpoint, the problem here is that this endpoint returns an array of sites.. From there how do I know which side ID I should pull over? Do we pull them all and create internally webflow integrations for all of them?

2022-08-23 12:05 UTC, sromic commented on sources/catalog/webflow/types.ts
> +export type WebflowWebook = {
That have been already deleted.

2022-08-23 19:40 UTC, paulkr commented on sources/catalog/webflow/webflow.ts
> +
Great point! Is there any way to pull the `shortName` from the API, given the site URL? If not, the Site ID should remain in the required authentication fields.

2022-08-24 08:30 UTC, sromic commented on sources/catalog/webflow/webflow.ts
> +
Okay, I made a research on this, and basically each generated API key is unique to each created site :)
So with that being said, we can then just use a given API Key to get site id (even it returns an array of sites, there is always just one site).

I'll refactor a code removing site id as a required param and get it under the hood.

2022-09-01 17:35 UTC, sromic commented
> Please update the tests accordingly to the requested changes.

Test were also updated accordingly.

2022-09-06 22:25 UTC, paulkr approved these changes

2022-09-06 22:25 UTC, merged