feat: add Hubspot integration
buildable/connections pull request #72
Opened 2022-08-19 22:21 UTC by ilmerainen

2022-08-22 01:29 UTC, ilmerainen commented
The docs say:
> For property change subscriptions, you will need to specify which property you want to be notified of. You can specify multiple property change subscriptions. If a customer's account doesn't have the property you specify in a subscription, you will not get any webhooks from that customer for that property.

It seems that with this interface there is no ability to handle this case.

Also, where can I specify the docs regarding the scopes required for authentication?

2022-08-22 21:14 UTC, moekatib requested changes
Initial review 1 of 2.

2022-08-22 21:14 UTC, moekatib commented on sources/catalog/hubspot/CHANGELOG.md
> +All notable changes to the `PagerDuty` Connection will be documented in this file.
Did you mean Hubspot? 😅

2022-08-22 21:14 UTC, moekatib commented on sources/catalog/hubspot/config.json
> +  "eventSchema": [
Should this be an object instead of an array?

2022-08-22 21:14 UTC, moekatib commented on sources/catalog/hubspot/helpers.ts
> +const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
Please move the contents of this file into the class (below or above the class). Our system dismisses any files that are not part of the initial approved files.

2022-08-22 21:14 UTC, moekatib commented on sources/catalog/hubspot/hubspot.ts
> +    developerApiKey: string;
The naming here needs to match the naming provided in the config.json file, for example `HUBSPOT_APP_DEVELOPER_API_KEY`

2022-08-22 21:15 UTC, moekatib commented on sources/catalog/hubspot/config.json
> +      "name": "HUBSPOT_APP_DEVELOPER_API_KEY",
Maybe drop the _APP, so just the HUBSPOT_DEVELOPER_API_KEY. For all 3?

2022-08-23 01:15 UTC, ilmerainen commented on sources/catalog/hubspot/config.json
> +  "eventSchema": [
This sample event payload was taken from the Hubspot developer account, Webhooks – Event subscriptions.

2022-08-23 01:33 UTC, ilmerainen commented on sources/catalog/hubspot/config.json
> +      "name": "HUBSPOT_APP_DEVELOPER_API_KEY",
Dropped _APP except for HUBSPOT_APP_ID.

2022-08-27 00:44 UTC, ilmerainen commented
@moekatib Changes made to comments. Can be reviewed

2022-08-30 18:40 UTC, paulkr requested changes

2022-08-30 18:40 UTC, paulkr commented on sources/catalog/hubspot/config.json
> +  "eventSchema": [
This should be an object, not an array of objects

2022-08-30 20:01 UTC, ilmerainen commented on sources/catalog/hubspot/config.json
> +  "eventSchema": [
This event schema is a real schema that comes from Hubspot. If this field stands for the example of event payload this current event schema exactly corresponds to it.
Could you please tell me what this field stands for?
<img width="995" alt="image" src="https://user-images.githubusercontent.com/53110715/187531534-9263fe17-84d5-4569-a85f-f619449725f1.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/53110715/187531669-3e701382-b4ec-4073-94b2-9f7ac3568415.png">

2022-08-30 20:06 UTC, ilmerainen commented on sources/catalog/hubspot/config.json
> +  "eventSchema": [
Also, please give me final feedback on what I need to change in order to approve this PR. It's been a long time since the PR was created, but you asked for ASAP.

2022-08-30 20:42 UTC, paulkr approved these changes

2022-08-30 20:42 UTC, paulkr approved these changes

2022-08-30 20:46 UTC, moekatib approved these changes

2022-08-30 20:49 UTC, merged