ADD - Ship station integration
buildable/connections pull request #74
Opened 2022-08-20 20:50 UTC by sromic

Added ShipStation integration

2022-08-30 20:49 UTC, paulkr requested changes
Looks great so far!

2022-08-30 20:49 UTC, paulkr commented on sources/catalog/shipStation/config.json
> +  "platform": "shipStations",
Platform should be `shipstation`

2022-08-30 20:49 UTC, paulkr commented on sources/catalog/shipStation/config.json
> +  "image": "https://assets.buildable.dev/catalog/node-templates/shipStation.svg",
https://assets.buildable.dev/catalog/node-templates/shipstation.svg

2022-08-30 20:49 UTC, paulkr commented on sources/catalog/shipStation/config.json
> +  "eventSchema": {
Is this all the data available for a sample event payload?

2022-08-30 20:49 UTC, paulkr commented on sources/catalog/shipStation/config.json
> +  "connectionTypes": ["source", "action"],
The value here should just be `["source"]`

2022-08-30 20:49 UTC, paulkr commented on sources/catalog/shipStation/shipStation.ts
> +import axios, { AxiosInstance, AxiosResponse } from "axios";
This file name should be in all lowercase: `shipstation.ts`

2022-08-31 10:13 UTC, sromic commented on sources/catalog/shipStation/config.json
> +  "eventSchema": {
Yes, 
payload for all events looks like the same, having only two properties:

e.g.

```
{
  "resource_url": "https://ssapi11.shipstation.com/shipments?batchId=123456&includeShipmentItems=True",
  "resource_type": "ITEM_SHIP_NOTIFY"
}
```

Also, headers do not include any specific/useful information, e.g.

```
connection    close
accept-encoding    gzip, deflate
content-length    139
host    webhook.site
content-type    application/json
accept    application/json, application/xml, text/json, text/x-json, text/javascript, text/xml
x-newrelic-transaction    PxRTUgUFXAtWBlZWA1RSA1MJFB8EBw8RVU4aBgtbUlYLA1tWBVVWBwEBD0NKQVkHBAZTUAUHFTs=
x-newrelic-id    VQMHVVRSGwABU1NRBgYGXw==
```

2022-08-31 19:05 UTC, merged