add square integration
buildable/connections pull request #83
Opened 2022-08-24 00:25 UTC by christianllv

2022-08-30 21:45 UTC, paulkr requested changes
Great work so far! Please update the tests accordingly as well.

2022-08-30 21:45 UTC, paulkr commented on sources/catalog/square/config.json
> +    "id": "_.body.event_id",
This should be the path for the webhook ID

2022-08-30 21:45 UTC, paulkr commented on sources/catalog/square/config.json
> +    "action"
There are no action templates currently, so connectionTypes should be `["source"]`

2022-08-30 21:45 UTC, paulkr commented on sources/catalog/square/config.json
> +  "events": [
For all events, please provide the description found here:

https://developer.squareup.com/reference/square/webhooks

2022-08-30 21:45 UTC, paulkr commented on sources/catalog/square/Square.ts
> +    return hash === signature;
If the verification does not match, an error must be thrown

2022-08-31 02:28 UTC, christianllv commented on sources/catalog/square/Square.ts
> +    return hash === signature;
Ok, I will thrown an error, but I saw some integrations that just return a boolean, including the Github sample integration.

2022-08-31 04:06 UTC, christianllv commented on sources/catalog/square/config.json
> +  "events": [
The descriptions were updated. We have some events that don't have descriptions. These events were added because existing on the ```getEventList``` API.

2022-08-31 22:19 UTC, christianllv commented on sources/catalog/square/config.json
> +    "id": "_.body.event_id",
The webhook is not received on payload events. Should I put the path from the "create webhook" method response?

2022-09-01 16:24 UTC, paulkr approved these changes

2022-09-01 16:24 UTC, paulkr commented on sources/catalog/square/config.json
> +    "id": "_.body.event_id",
Correct, it refers to the path for the webhook id in the response from the "create webhook" method.

2022-09-01 16:24 UTC, merged